// Mock data for Musika Marketplace

export const categories = [
  { id: 'accommodation', name: 'Accommodation', count: 1250, icon: 'Building' },
  { id: 'dining', name: 'Dining', count: 250, icon: 'UtensilsCrossed' },
  { id: 'transportation', name: 'Transportation', count: 650, icon: 'Car' },
  { id: 'legal', name: 'Legal & Documentation', count: 50, icon: 'Scale' },
  { id: 'healthcare', name: 'Healthcare & Wellness', count: 150, icon: 'Heart' },
  { id: 'beauty', name: 'Beauty', count: 550, icon: 'Sparkles' },
  { id: 'shopping', name: 'Shopping Mall', count: 400, icon: 'ShoppingBag' },
  { id: 'electronics', name: 'Electronics & Gadgets', count: 250, icon: 'Smartphone' },
];

export const locations = [
  { id: 'near-campus', name: 'Near Campus', count: 850 },
  { id: 'suburb', name: 'Suburb', count: 150 },
  { id: 'residential', name: 'Residential Areas', count: 50 },
  { id: 'city-center', name: 'Near City Center', count: 350 },
  { id: 'online', name: 'Online', count: 650 },
];

export const supportedLanguages = [
  'English',
  'Portuguese',
  'Shona',
  'Arabic',
  'Hindi',
  'Zulu',
  'Xhosa',
];

function hashSeed(seed: string): number {
  let hash = 0;
  for (let index = 0; index < seed.length; index += 1) {
    hash = (hash * 31 + seed.charCodeAt(index)) >>> 0;
  }
  return hash;
}

export function getDeterministicLanguages(seed: string | number, count = 3): string[] {
  const normalizedSeed = String(seed);
  const pool = [...supportedLanguages];
  const picked: string[] = [];
  let cursor = hashSeed(normalizedSeed);

  while (picked.length < Math.min(count, pool.length)) {
    const nextIndex = cursor % pool.length;
    picked.push(pool.splice(nextIndex, 1)[0]);
    cursor = hashSeed(`${cursor}-${normalizedSeed}-${picked.length}`);
  }

  return picked;
}

export function getVendorAvatarUrl(vendorName: string): string {
  const seed = encodeURIComponent(vendorName.trim() || 'vendor');
  return `https://api.dicebear.com/8.x/initials/svg?seed=${seed}&backgroundType=gradientLinear`;
}

// Accommodation Services
export const accommodationServices = [
  {
    id: 1,
    title: 'Greenview Apartments',
    category: 'accommodation',
    tags: ['Highly Recommended', 'Trusted'],
    description: 'Fully furnished studio apartments with private balconies and study desks. Perfect for focused academic life.',
    features: ['Private Rooms', 'In-Unit Laundry', 'Nearby Campus', '24/7 Security'],
    price: 320,
    priceUnit: 'month',
    rating: 4.8,
    reviews: 124,
    vendor: 'Global Student Homes',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop',
  },
  {
    id: 2,
    title: 'Homestay Haven',
    category: 'accommodation',
    tags: ['Cultural Immersion', 'Modern'],
    description: 'Live with a local host family. Great for language learning and cultural exchange.',
    features: ['Language Support', 'Airport Pickup', 'Private Room', 'Daily Meals'],
    price: 250,
    priceUnit: 'month',
    rating: 4.7,
    reviews: 85,
    vendor: 'Welcome Stay Network',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop',
  },
  {
    id: 3,
    title: 'Campus Link Dorms',
    category: 'accommodation',
    tags: ['Popular Choice', 'On-Campus'],
    description: 'University-affiliated dormitory with direct access to campus facilities and student events.',
    features: ['Meal Plan Included', 'Gym Access', 'Resident Advisors', 'Study Lounges'],
    price: 220,
    priceUnit: 'month',
    rating: 4.5,
    reviews: 203,
    vendor: 'Campus Link',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop',
  },
  {
    id: 4,
    title: 'Urban Nest Hostel',
    category: 'accommodation',
    tags: ['Budget Friendly', 'Campus'],
    description: 'Cozy shared rooms in campus. Ideal for students who want affordability without sacrificing location.',
    features: ['Free Wi-Fi', 'Weekly Cleaning', '24/7 Security', 'Shared Kitchen'],
    price: 150,
    priceUnit: 'month',
    rating: 4.3,
    reviews: 167,
    vendor: 'Student Stay Co.',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&auto=format&fit=crop',
  },
];

// Electronics & Gadgets Products
export const electronicsProducts = [
  {
    id: 101,
    title: 'Wireless Noise-Canceling Headphones',
    category: 'electronics',
    tags: ['Best Seller', 'Student Discount'],
    description: 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and comfortable over-ear design perfect for studying.',
    features: ['Bluetooth 5.0', '30hr Battery', 'Active NC', 'Foldable'],
    price: 89,
    priceUnit: 'item',
    rating: 4.6,
    reviews: 342,
    vendor: 'TechHub India',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop',
  },
  {
    id: 102,
    title: 'Portable Laptop Stand',
    category: 'electronics',
    tags: ['Affordable', 'Ergonomic'],
    description: 'Adjustable aluminum laptop stand for better posture. Lightweight and foldable for easy carrying to classes.',
    features: ['Adjustable Height', 'Aluminum Build', 'Foldable', 'Universal Fit'],
    price: 24,
    priceUnit: 'item',
    rating: 4.4,
    reviews: 128,
    vendor: 'StudySmart Store',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop',
  },
  {
    id: 103,
    title: 'Wireless Bluetooth Speaker',
    category: 'electronics',
    tags: ['Portable', 'Waterproof'],
    description: 'Compact wireless speaker with 360-degree sound, waterproof design, and 12-hour playtime. Perfect for dorm rooms.',
    features: ['IPX7 Waterproof', '12hr Playtime', '360° Sound', 'Bluetooth 5.0'],
    price: 45,
    priceUnit: 'item',
    rating: 4.5,
    reviews: 89,
    vendor: 'AudioZone',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop',
  },
  {
    id: 104,
    title: 'USB-C Hub Multi-Port Adapter',
    category: 'electronics',
    tags: ['Essential', 'Multi-function'],
    description: '7-in-1 USB-C hub with HDMI, USB 3.0, SD card reader, and PD charging. Essential for modern laptops.',
    features: ['7 Ports', '4K HDMI', 'PD Charging', 'Compact'],
    price: 35,
    priceUnit: 'item',
    rating: 4.7,
    reviews: 256,
    vendor: 'TechEssentials',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1625766763788-95dcce9bf5ac?w=800&auto=format&fit=crop',
  },
  {
    id: 105,
    title: 'Mechanical Keyboard RGB',
    category: 'electronics',
    tags: ['Gaming', 'Backlit'],
    description: 'Compact mechanical keyboard with customizable RGB lighting, blue switches for tactile feedback. Great for coding and gaming.',
    features: ['RGB Backlight', 'Blue Switches', 'Anti-ghosting', 'Compact 60%'],
    price: 55,
    priceUnit: 'item',
    rating: 4.8,
    reviews: 178,
    vendor: 'GamerGear India',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&auto=format&fit=crop',
  },
  {
    id: 106,
    title: 'Wireless Mouse Ergonomic',
    category: 'electronics',
    tags: ['Comfortable', 'Long Battery'],
    description: 'Ergonomic wireless mouse with 2.4GHz connectivity, adjustable DPI, and 18-month battery life.',
    features: ['Ergonomic Design', 'Adjustable DPI', 'Silent Clicks', '18mo Battery'],
    price: 18,
    priceUnit: 'item',
    rating: 4.3,
    reviews: 412,
    vendor: 'TechHub India',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop',
  },
];

// Beauty Products
export const beautyProducts = [
  {
    id: 201,
    title: 'Student Skincare Bundle',
    category: 'beauty',
    tags: ['Natural', 'Vegan'],
    description: 'Complete skincare set with cleanser, toner, and moisturizer. Formulated for all skin types with natural ingredients.',
    features: ['All Skin Types', 'Natural Ingredients', 'Cruelty-Free', 'Travel Size'],
    price: 32,
    priceUnit: 'item',
    rating: 4.5,
    reviews: 89,
    vendor: 'GlowUp Beauty',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop',
  },
  {
    id: 202,
    title: 'Professional Hair Dryer',
    category: 'beauty',
    tags: ['Salon Quality', 'Fast Drying'],
    description: 'Ionic hair dryer with multiple heat settings, cool shot button, and concentrator nozzle for salon-quality results.',
    features: ['Ionic Technology', '3 Heat Settings', 'Cool Shot', 'Lightweight'],
    price: 42,
    priceUnit: 'item',
    rating: 4.6,
    reviews: 156,
    vendor: 'StyleStudio',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=800&auto=format&fit=crop',
  },
  {
    id: 203,
    title: 'Makeup Starter Kit',
    category: 'beauty',
    tags: ['Complete Set', 'Beginner Friendly'],
    description: 'Essential makeup kit with foundation, mascara, eyeshadow palette, and lip tint. Perfect for beginners.',
    features: ['8 Products', 'Long-Lasting', 'Hypoallergenic', 'Tutorial Included'],
    price: 28,
    priceUnit: 'item',
    rating: 4.4,
    reviews: 234,
    vendor: 'BeautyBox India',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&auto=format&fit=crop',
  },
  {
    id: 204,
    title: 'Beard Grooming Kit',
    category: 'beauty',
    tags: ['For Men', 'Complete Kit'],
    description: 'Complete beard care set with beard oil, balm, comb, and trimmer. Keep your beard looking sharp.',
    features: ['Beard Oil', 'Balm', 'Comb', 'Trimmer'],
    price: 38,
    priceUnit: 'item',
    rating: 4.7,
    reviews: 67,
    vendor: 'MensGrooming Co.',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop',
  },
  {
    id: 205,
    title: 'Organic Shampoo & Conditioner Set',
    category: 'beauty',
    tags: ['Sulfate-Free', 'Organic'],
    description: 'Gentle, sulfate-free shampoo and conditioner set with argan oil. Suitable for daily use.',
    features: ['Sulfate-Free', 'Argan Oil', 'All Hair Types', '500ml Each'],
    price: 22,
    priceUnit: 'item',
    rating: 4.3,
    reviews: 189,
    vendor: 'PureCare Products',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&auto=format&fit=crop',
  },
];

// Healthcare & Wellness Products
export const healthcareProducts = [
  {
    id: 301,
    title: 'Digital Thermometer',
    category: 'healthcare',
    tags: ['Essential', 'Fast Reading'],
    description: 'Accurate digital thermometer with fever alarm, memory function, and quick 10-second reading.',
    features: ['10-sec Reading', 'Fever Alarm', 'Memory Function', 'FDA Approved'],
    price: 15,
    priceUnit: 'item',
    rating: 4.6,
    reviews: 423,
    vendor: 'HealthFirst Medical',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop',
  },
  {
    id: 302,
    title: 'First Aid Kit - 100 Pieces',
    category: 'healthcare',
    tags: ['Complete', 'Travel Size'],
    description: 'Comprehensive first aid kit with bandages, antiseptic wipes, gauze, and more. Compact case for dorm or travel.',
    features: ['100 Pieces', 'Compact Case', 'Emergency Guide', 'Refillable'],
    price: 19,
    priceUnit: 'item',
    rating: 4.8,
    reviews: 312,
    vendor: 'SafeCare Supplies',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=800&auto=format&fit=crop',
  },
  {
    id: 303,
    title: 'Yoga Mat - Non Slip',
    category: 'healthcare',
    tags: ['Exercise', 'Eco-Friendly'],
    description: 'Premium TPE yoga mat with excellent grip, 6mm thickness for joint protection, and carrying strap included.',
    features: ['Non-Slip Surface', '6mm Thick', 'Eco-Friendly TPE', 'Carrying Strap'],
    price: 28,
    priceUnit: 'item',
    rating: 4.5,
    reviews: 178,
    vendor: 'FitLife Wellness',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&auto=format&fit=crop',
  },
  {
    id: 304,
    title: 'Vitamin D3 Supplements',
    category: 'healthcare',
    tags: ['Immunity', '180 Tablets'],
    description: 'High-potency Vitamin D3 (2000 IU) for immune support and bone health. 6-month supply.',
    features: ['2000 IU', '180 Tablets', 'Immune Support', 'Non-GMO'],
    price: 16,
    priceUnit: 'item',
    rating: 4.7,
    reviews: 89,
    vendor: 'NutriWell Supplements',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop',
  },
  {
    id: 305,
    title: 'Resistance Bands Set',
    category: 'healthcare',
    tags: ['Home Workout', '5 Levels'],
    description: 'Set of 5 resistance bands with different strength levels. Perfect for home workouts and physical therapy.',
    features: ['5 Resistance Levels', 'Door Anchor', 'Carrying Bag', 'Exercise Guide'],
    price: 21,
    priceUnit: 'item',
    rating: 4.4,
    reviews: 267,
    vendor: 'FitLife Wellness',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800&auto=format&fit=crop',
  },
  {
    id: 306,
    title: 'Meditation & Sleep Aid Device',
    category: 'healthcare',
    tags: ['Stress Relief', 'Sleep Better'],
    description: 'Smart sleep aid with guided breathing light, white noise, and nature sounds for better sleep and stress relief.',
    features: ['Breathing Light', 'White Noise', 'Nature Sounds', 'Rechargeable'],
    price: 48,
    priceUnit: 'item',
    rating: 4.6,
    reviews: 134,
    vendor: 'MindfulLiving',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1515023115689-589c33041697?w=800&auto=format&fit=crop',
  },
];

// Dining Products
export const diningProducts = [
  {
    id: 401,
    title: 'Student Meal Plan - Weekly',
    category: 'dining',
    tags: ['Healthy', 'Affordable'],
    description: 'Weekly meal plan with 14 nutritious meals delivered to your dorm. Vegetarian and non-vegetarian options available.',
    features: ['14 Meals/Week', 'Fresh Daily', 'Customizable', 'Free Delivery'],
    price: 49,
    priceUnit: 'week',
    rating: 4.5,
    reviews: 89,
    vendor: 'CampusKitchen',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&auto=format&fit=crop',
  },
  {
    id: 402,
    title: 'Electric Rice Cooker 1L',
    category: 'dining',
    tags: ['Essential', 'Compact'],
    description: 'Compact rice cooker perfect for dorm rooms. Cooks rice, steams vegetables, and keeps food warm.',
    features: ['1L Capacity', 'Non-Stick Pot', 'Keep Warm', 'Compact'],
    price: 32,
    priceUnit: 'item',
    rating: 4.6,
    reviews: 234,
    vendor: 'DormLife Essentials',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&auto=format&fit=crop',
  },
];

// Transportation Services
export const transportationServices = [
  {
    id: 501,
    title: 'Airport Pickup Service',
    category: 'transportation',
    tags: ['High Recommended', 'Trusted'],
    description: 'Safe airport pickup service with guided city orientation tour. Perfect introduction to newly arrived students.',
    features: ['Multilingual Drivers', 'Meet & Greet', 'City Tour Included', 'Available 24/7'],
    price: 50,
    priceUnit: 'trip',
    rating: 4.9,
    reviews: 428,
    vendor: 'Student Welcome Services',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&auto=format&fit=crop',
  },
  {
    id: 502,
    title: 'Monthly Bus Pass',
    category: 'transportation',
    tags: ['Student Discount', 'Unlimited'],
    description: 'Unlimited bus travel within city limits. Valid for all city buses with student ID.',
    features: ['Unlimited Rides', 'All Routes', 'Student Price', 'Easy Renewal'],
    price: 25,
    priceUnit: 'month',
    rating: 4.7,
    reviews: 567,
    vendor: 'City Transit Authority',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&auto=format&fit=crop',
  },
  {
    id: 503,
    title: 'Bike Rental - Monthly',
    category: 'transportation',
    tags: ['Eco-Friendly', 'Exercise'],
    description: 'Reliable bicycle rental with helmet and lock included. Perfect for getting around campus.',
    features: ['Helmet Included', 'Bike Lock', 'Maintenance Free', 'Easy Return'],
    price: 18,
    priceUnit: 'month',
    rating: 4.4,
    reviews: 123,
    vendor: 'CampusCycles',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&auto=format&fit=crop',
  },
];

// Legal & Documentation Services
export const legalServices = [
  {
    id: 601,
    title: 'Legal Consultation',
    category: 'legal',
    tags: ['Professional', 'Experienced'],
    description: 'Professional legal advice for visa issues, tenancy problems and other legal matters affecting international students.',
    features: ['Multilingual', 'Licensed', 'Visa Extensions', 'Available 24/7'],
    price: 10,
    priceUnit: 'consultation',
    rating: 4.8,
    reviews: 156,
    vendor: 'Student Legal Consultants',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop',
  },
  {
    id: 602,
    title: 'Document Attestation Service',
    category: 'legal',
    tags: ['Fast', 'Reliable'],
    description: 'Quick document attestation for academic certificates, transcripts, and other important documents.',
    features: ['Fast Processing', 'All Documents', 'Pickup & Delivery', 'Certified'],
    price: 35,
    priceUnit: 'document',
    rating: 4.6,
    reviews: 89,
    vendor: 'DocuLegal Services',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&auto=format&fit=crop',
  },
];

// Combined services array for the Services page
export const services = [
  ...accommodationServices,
  ...electronicsProducts,
  ...beautyProducts,
  ...healthcareProducts,
  ...diningProducts,
  ...transportationServices,
  ...legalServices,
];

// Shopping Mall Products (for Marketplace)
export const marketplaceProducts = [
  {
    id: 1001,
    name: 'Mazoe Orange Crush 2L',
    vendor: 'Delta Beverages Zimbabwe',
    vendorVerified: true,
    price: 150,
    currency: '₹',
    description: 'Each bottle of Mazoe Orange Crush bursts with rich orange juice flavour, delivering the signature tangy taste that\'s uniquely Mazoe.',
    image: 'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=800&auto=format&fit=crop',
    rating: 4.7,
    reviews: 89,
    category: 'Beverages',
    subcategory: 'Juices',
  },
  {
    id: 1002,
    name: 'Bally House 2L',
    vendor: 'Bally House Foods',
    price: 100,
    originalPrice: 150,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=400&auto=format&fit=crop',
    subcategory: 'Drinks',
  },
  {
    id: 1003,
    name: 'Ace Mealie Meal 5kg',
    vendor: 'Ace Milling',
    price: 400,
    originalPrice: 499,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop',
    subcategory: 'Cereals',
  },
  {
    id: 1004,
    name: 'Pfuko Maheu 250ml',
    vendor: 'Pfuko Foods',
    price: 50,
    originalPrice: 80,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&auto=format&fit=crop',
    subcategory: 'Drinks',
  },
  {
    id: 1005,
    name: 'Cerevita 200g',
    vendor: 'Cerevita',
    price: 150,
    originalPrice: 250,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?w=400&auto=format&fit=crop',
    subcategory: 'Cereals',
  },
  {
    id: 1006,
    name: 'Lager 340ml',
    vendor: 'Lager Co.',
    price: 80,
    originalPrice: 100,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=400&auto=format&fit=crop',
    subcategory: 'Drinks',
  },
  {
    id: 1007,
    name: 'Fresh Apple Pack 1kg',
    vendor: 'Campus Fresh Mart',
    price: 220,
    originalPrice: 260,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&auto=format&fit=crop',
    subcategory: 'Fruits',
  },
  {
    id: 1008,
    name: 'Banana Bunch',
    vendor: 'Campus Fresh Mart',
    price: 80,
    originalPrice: 100,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?w=400&auto=format&fit=crop',
    subcategory: 'Fruits',
  },
  {
    id: 1009,
    name: 'Tomato Basket 1kg',
    vendor: 'Green Basket',
    price: 70,
    originalPrice: 90,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=400&auto=format&fit=crop',
    subcategory: 'Vegetables',
  },
  {
    id: 1010,
    name: 'Carrot Pack 500g',
    vendor: 'Green Basket',
    price: 60,
    originalPrice: 75,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1447175008436-170170753d52?w=400&auto=format&fit=crop',
    subcategory: 'Vegetables',
  },
  {
    id: 1011,
    name: 'Plantain Chips 200g',
    vendor: 'Snack Stop',
    price: 90,
    originalPrice: 120,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&auto=format&fit=crop',
    subcategory: 'Snacks',
  },
  {
    id: 1012,
    name: 'Mixed Nut Snack Pack',
    vendor: 'Snack Stop',
    price: 140,
    originalPrice: 170,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400&auto=format&fit=crop',
    subcategory: 'Snacks',
  },
];

// Featured Vendors
export const featuredVendors = [
  {
    id: 1,
    name: 'Cavendish Shopping Mall',
    rating: 4.8,
    reviews: 245,
    image: 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=400&auto=format&fit=crop',
  },
  {
    id: 2,
    name: 'Legends Wellness Hub',
    rating: 4.9,
    reviews: 189,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&auto=format&fit=crop',
  },
  {
    id: 3,
    name: 'Lalita Roongta Apartments',
    rating: 4.7,
    reviews: 312,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&auto=format&fit=crop',
  },
];

// Popular Services
export const popularServices = [
  {
    id: 1,
    title: 'Airport Pickup',
    category: 'Transportation',
    tags: ['High Recommended', 'Trusted'],
    description: 'Safe airport pickup service with guided city orientation tour. Perfect introduction to newly arrived students.',
    features: ['Multilingual Drivers', 'Meet & Greet', 'City Tour Included', 'Available 24/7'],
    price: 50,
    priceUnit: 'trip',
    rating: 4.9,
    reviews: 428,
    vendor: 'Student Welcome Services',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&auto=format&fit=crop',
  },
  {
    id: 2,
    title: 'Legal Consultation',
    category: 'Legal',
    tags: ['Professional', 'Experienced'],
    description: 'Professional legal advice for visa issues, tenancy problems and other legal matters affecting international students.',
    features: ['Multilingual', 'Licensed', 'Visa Extensions', 'Available 24/7'],
    price: 10,
    priceUnit: 'consultation',
    rating: 4.8,
    reviews: 156,
    vendor: 'Student Legal Consultants',
    vendorVerified: true,
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop',
  },
];

// Features for landing page
export const features = [
  {
    id: 1,
    title: 'Verified Vendors',
    description: 'Every vendor is verified through student ID and university email confirmation. Shop with confidence knowing you\'re dealing with real students.',
    icon: 'ShieldCheck',
  },
  {
    id: 2,
    title: 'High Quality Guarantee',
    description: 'All products undergo quality checks and come with our satisfaction guarantee. Return policy ensures you get exactly what you expect',
    icon: 'Award',
  },
  {
    id: 3,
    title: 'Authentic Student Reviews',
    description: 'Connect directly with fellow students who understand your needs. Get insider tips and recommendations from your peers.',
    icon: 'MessageCircle',
  },
  {
    id: 4,
    title: 'Secure Transactions',
    description: 'Secure payment processing with buyer protection. Escrow service holds payments until you confirm receipt and satisfaction.',
    icon: 'Lock',
  },
];

// How it works steps
export const howItWorks = [
  {
    step: 1,
    title: 'Browse Verified Vendors',
    description: 'Explore products from verified student vendors in your university or city. Filter by location, category, and ratings to find exactly what you need.',
  },
  {
    step: 2,
    title: 'Choose Quality Products',
    description: 'Select from high-quality products with detailed descriptions, photos, and reviews. Chat directly with vendors to ask questions before purchasing.',
  },
  {
    step: 3,
    title: 'Complete Secure Transaction',
    description: 'Pay securely through our protected payment system. Meet in safe campus locations or use our verified shipping options for distant purchases.',
  },
];

// Footer links
export const footerLinks = {
  forStudents: [
    { label: 'Browse Services', href: '/services' },
    { label: 'How it works', href: '#' },
    { label: 'Buyer Protection', href: '#' },
    { label: 'Payment Methods', href: '#' },
    { label: 'Shipping Info', href: '#' },
  ],
  forVendors: [
    { label: 'Start Selling', href: '#' },
    { label: 'Vendor Guidelines', href: '#' },
    { label: 'Verification Process', href: '#' },
    { label: 'Seller Tools', href: '#' },
    { label: 'Success Stories', href: '#' },
  ],
  support: [
    { label: 'Help Center', href: '#' },
    { label: 'Contact Us', href: '#' },
    { label: 'Safety Guidelines', href: '#' },
    { label: 'Report an Issue', href: '#' },
    { label: 'Community Forum', href: '#' },
  ],
};
